name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtool libtool-bin autoconf automake pkg-config python3-pip

      - name: Install buildozer
        run: pip install buildozer cython

      - name: Build APK
        run: yes y | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: macroff-apk
          path: bin/*.apk
